"""company_address unique=alse from ompoanys table

Revision ID: aa004d06f699
Revises: 7c80c9a32633
Create Date: 2025-04-11 13:09:29.857986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa004d06f699"
down_revision: Union[str, None] = "7c80c9a32633"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "companys_company_address_key", "companys", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "companys_company_address_key", "companys", ["company_address"]
    )
    # ### end Alembic commands ###
