"""added username and active fields to ser table

Revision ID: 7c80c9a32633
Revises: 0776c6685ecd
Create Date: 2025-04-09 10:48:42.571094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c80c9a32633"
down_revision: Union[str, None] = "0776c6685ecd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("username", sa.String(length=50), nullable=False)
    )
    op.add_column("users", sa.Column("active", sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "active")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
