"""add company_description

Revision ID: a79337990da3
Revises: 37a739f16cfd
Create Date: 2025-04-02 11:55:46.679616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a79337990da3"
down_revision: Union[str, None] = "37a739f16cfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companys",
        sa.Column("company_description", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companys", "company_description")
    # ### end Alembic commands ###
